### ISSUE TITLE
Provide way to extend datasources

### ISSUE THREAD

**Issue by tuchk4** [tuchk4/bivrost#1]
extends - but not override whole **methodProperties** section.

for example **serialize** method could be defined at base data source but **api** and **prepeare** methods - at child data source.

or maybe change way to configure data source

**Comment by tuchk4** [comment]
@corporateanon Any ideas?)

**Comment by corporateanon** [comment]
it should work this way

**Comment by corporateanon** [comment]
Somewhere in this lines. I dont remember.
https://github.com/frankland/bivrost/blob/master/src/data/source.js#L7-L37
